# Generated by Django 4.2.7 on 2025-09-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0001_initial"),
        ("events", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="transport_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transport.transportservice",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="allowed_categories",
            field=models.ManyToManyField(blank=True, to="events.category"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="excluded_events",
            field=models.ManyToManyField(blank=True, to="events.event"),
        ),
    ]
